# Site settings
title: kaLki Blog - Info Sec, CTF & Hacking # Tumhara title
author: kaLki # Tumhara naam
email: kalkibusinesofficial@gmail.com # Tumhara email
description: > # Tumhara description
  Info Sec, CTF & Hacking
show_excerpts: true # Homepage pe post ka excerpt dikhega

# Sass settings (css ke liye)
sass:
  sass_dir: _sass # Yeh theek hai

# Remote Theme settings
remote_theme: jekyll/plainwhite-theme # Yeh line top level par rahegi

# Plainwhite theme specific settings
plainwhite: # <--- Yeh line bilkul left side se shuru hogi (koi indentation nahi)
  name: kaLki # <--- Yeh line plainwhite: se theek 2 space aage se shuru hogi
  tagline: bug hunter # <--- Yeh bhi plainwhite: se 2 space aage
  date_format: "%b %-d, %Y" # <--- Yeh bhi plainwhite: se 2 space aage
  sitemap: true # <--- Yeh bhi plainwhite: se 2 space aage

  # Social links
  social_links: # <--- Yeh line plainwhite: se 2 space aage
    twitter: kalki_x0 # <--- Yeh line social_links: se 2 space aage (total 4 space shuru se)
    github: kalki_x0 # <--- Yeh bhi social_links: se 2 space aage (total 4 space shuru se)
    linkedIn: /in/kalki-x0 # <--- LinkedIn ke liye poora path lagta hai /in/ ke saath. Check kar lena tumhara kya path hai.
    rss: /feed.xml # <--- Yeh bhi social_links: se 2 space aage (total 4 space shuru se)
    # Agar koi aur link lagana hai (jaise instagram:), toh uske aage se # hata dena aur same indentation (4 space shuru se) maintain karna.

# Header pages (optional)
# Agar koi page header mein link karna hai, toh neeche # hata kar add karo, jaise:
# header_pages:
#   - about.md

# Build settings
# Jab remote_theme use karte hain, toh yeh 'theme: plainwhite' wali line nahi chahiye. Isse hata dena.
# theme: plainwhite # <--- IS LINE KO HATA DO

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme # Yeh plugin add kar lo, confirm ho jayega ki remote theme support enabled hai
