# Site settings
title: kaLki Blog - Info Sec, CTF & Hacking # Tumhara title
author: kaLki # Tumhara naam
email: kalkibusinesofficial@gmail.com # Tumhara email
description: > # Tumhara description (Yeh ">" ke baad ek space dekar neeche likhte hain)
  Info Sec, CTF & Hacking
show_excerpts: true # Homepage pe post ka excerpt dikhega (true ya false)

# Sass settings (CSS ke liye)
sass:
  sass_dir: _sass # Default setting, usually theek hai

# Remote Theme settings
# Yeh batata hai ki theme GitHub par kis repository se lena hai
remote_theme: samarsault/plainwhite-jekyll

# Plainwhite theme specific settings
# Yeh block Plainwhite theme ki apni settings ke liye hai
plainwhite:
  name: kaLki # <-- Yeh naam sidebar mein avatar ke neeche dikhta hai
  tagline: bug hunter # <-- Yeh chota sa title ya tagline naam ke neeche
  date_format: "%b %-d, %Y" # <-- Blog post dates ka format
  sitemap: true # <-- Sitemap generate karega (true ya false)

  # Social links
  # Yahan apne social media profiles ke username/path daalo
  social_links:
    twitter: kalki_x0 # <-- Twitter username
    github:  kalki_x0 # <-- GitHub username
    linkedIn: /in/kalki-x0 # <-- LinkedIn public profile path (/in/ wala part)
    rss: /feed.xml # <-- RSS feed link (blog ke liye)
    # Agar koi aur link lagana hai (jaise instagram, facebook, youtube), toh uske aage se # hata dena aur apna username/ID likh dena. Indentation (shuru se 4 space) maintain karna.
    # instagram: your_instagram_username
    # facebook: your_facebook_username

# Header pages (optional)
# Agar koi specific page header mein link karna hai (jaise About, Projects), toh neeche uncomment karke un files ka path add karo.
# header_pages:
#   - about.md
#   - projects.md

# Build settings
# Jab remote_theme use karte hain, toh yeh 'theme:' wali line nahi chahiye. Isse commented hi rehne do ya hata do.
# theme: plainwhite

# Plugins needed for GitHub Pages and remote theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # <--- Remote theme use karne ke liye yeh plugin zaroori hai
